server:
  port: 8114

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NeilRen/SpringCloudDemo.git
          search-paths: springcloud-config
#          username:
#          password:
#          basedir:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"