server:
  port: 18080

spring:
  application:
    name: DemoService

eureka:
  client:
    #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/