server:
  port: 18080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  stream:
    bindings:
      demoServiceMQ:
        group: demo
        content-type: application/json
      demoClientMQ:
        group: demo
        content-type: application/json
